Resources:
  MyQueueE6CA6235:
    Type: AWS::SQS::Queue
    Properties:
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 30
    Metadata:
      aws:cdk:path: CdkQueueDynamoDb/MyQueue/Resource
  CDKLambda1ServiceRole7CD1D82C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkQueueDynamoDb/CDK-Lambda1/ServiceRole/Resource
  CDKLambda1ServiceRoleDefaultPolicyD0DECAD1:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:ReceiveMessage
              - sqs:ChangeMessageVisibility
              - sqs:GetQueueUrl
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - MyQueueE6CA6235
                - Arn
          - Action:
              - dynamodb:BatchWriteItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - CDKQueueTable58865DC8
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: CDKLambda1ServiceRoleDefaultPolicyD0DECAD1
      Roles:
        - Ref: CDKLambda1ServiceRole7CD1D82C
    Metadata:
      aws:cdk:path: CdkQueueDynamoDb/CDK-Lambda1/ServiceRole/DefaultPolicy/Resource
  CDKLambda1C9BA2B3C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07S3Bucket28F94FDE
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07S3VersionKey2D191144
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07S3VersionKey2D191144
      Handler: index2.handler
      Role:
        Fn::GetAtt:
          - CDKLambda1ServiceRole7CD1D82C
          - Arn
      Runtime: nodejs10.x
      Environment:
        Variables:
          TABLE_NAME:
            Ref: CDKQueueTable58865DC8
    DependsOn:
      - CDKLambda1ServiceRoleDefaultPolicyD0DECAD1
      - CDKLambda1ServiceRole7CD1D82C
    Metadata:
      aws:cdk:path: CdkQueueDynamoDb/CDK-Lambda1/Resource
      aws:asset:path: asset.5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07
      aws:asset:property: Code
  CDKLambda1SqsEventSourceCdkQueueDynamoDbMyQueue8B4DB5535621DF79:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn:
        Fn::GetAtt:
          - MyQueueE6CA6235
          - Arn
      FunctionName:
        Ref: CDKLambda1C9BA2B3C
    Metadata:
      aws:cdk:path: CdkQueueDynamoDb/CDK-Lambda1/SqsEventSource:CdkQueueDynamoDbMyQueue8B4DB553/Resource
  CDKQueueTable58865DC8:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkQueueDynamoDb/CDK-Queue-Table/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.16.3,@aws-cdk/assets=1.17.1,@aws-cdk/aws-apigateway=1.17.1,@aws-cdk/aws-applicationautoscaling=1.17.1,@aws-cdk/aws-autoscaling-common=1.17.1,@aws-cdk/aws-cloudwatch=1.17.1,@aws-cdk/aws-dynamodb=1.17.1,@aws-cdk/aws-ec2=1.17.1,@aws-cdk/aws-events=1.17.1,@aws-cdk/aws-iam=1.17.1,@aws-cdk/aws-kms=1.17.1,@aws-cdk/aws-lambda=1.17.1,@aws-cdk/aws-lambda-event-sources=1.17.1,@aws-cdk/aws-s3=1.17.1,@aws-cdk/aws-s3-assets=1.17.1,@aws-cdk/aws-s3-notifications=1.17.1,@aws-cdk/aws-sns=1.17.1,@aws-cdk/aws-sns-subscriptions=1.17.1,@aws-cdk/aws-sqs=1.17.1,@aws-cdk/aws-ssm=1.17.1,@aws-cdk/core=1.17.1,@aws-cdk/cx-api=1.17.1,@aws-cdk/region-info=1.17.1,jsii-runtime=node.js/v12.13.0
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07S3Bucket28F94FDE:
    Type: String
    Description: S3 bucket for asset "5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07"
  AssetParameters5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07S3VersionKey2D191144:
    Type: String
    Description: S3 key for asset version "5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07"
  AssetParameters5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07ArtifactHash36F9ADDE:
    Type: String
    Description: Artifact hash for asset "5473c41f3de43faeb19ed4fe98692bf2f17177dcbf3e1a82b0ea7053937e4b07"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

